version: '3.8'

services:
  app:
    image: node:20 # ここで使用する Node.js のバージョンを指定します
    working_dir: /app # コンテナ内の作業ディレクトリ
    volumes:
      - ./blog_svelte/src:/app # ホストマシンの現在のディレクトリをコンテナにマウント
    ports:
      - "3000:3000" # ホストマシンのポート3000をコンテナのポート3000にマッピング
    command: sh -c "npm install && npm start && npm install express body-parser && npm install cors" # コンテナ起動時に実行されるコマンド
