name: Check Docker Hub Rate Limits
on: workflow_dispatch

jobs:
  check-rate-limits:
    runs-on: ubuntu-latest
    steps:
      - name: Pull an image anonymously
        run: docker pull alpine:latest

      - name: Check Rate Limits
        run: |
          # Docker HubのV2 APIをHEADリクエストで叩くことで、RateLimitヘッダーを取得できます。
          # ここでは例としてalpineイメージを使用しています。
          response=$(curl -s -I https://registry-1.docker.io/v2/library/alpine/manifests/latest)
          
          # レスポンスヘッダー全体を表示
          echo "$response"
          echo "----"

          # RateLimit-Remainingの値のみ抽出
          remaining=$(echo "$response" | grep -i "RateLimit-Remaining" | awk '{print $2}')
          
          echo "RateLimit-Remaining: $remaining"
