name: Check Docker Hub Rate Limits
on: workflow_dispatch

jobs:
  check-rate-limits:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Get anonymous token
        run: |
          # Docker Hubの匿名トークン取得
          TOKEN=$(curl -s "https://auth.docker.io/token?service=registry.docker.io&scope=repository:library/alpine:pull" | jq -r .token)
          echo "TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Check Rate Limits
        run: |
          # トークンを利用してRate Limit情報取得
          response=$(curl -sI -H "Authorization: Bearer $TOKEN" "https://registry-1.docker.io/v2/library/alpine/manifests/latest")
          echo "$response"
          echo "----"
          remaining=$(echo "$response" | grep -i "RateLimit-Remaining" | awk '{print $2}')
          echo "RateLimit-Remaining: $remaining"
