name: Check Docker Hub Rate Limits
on: workflow_dispatch

jobs:
  check-rate-limits:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Get anonymous token
        run: |
          # "repository:library/alpine:pull" のscopeで匿名トークンを取得する
          token=$(curl -s "https://auth.docker.io/token?service=registry.docker.io&scope=repository:library/alpine:pull" | jq -r .token)
          echo "token=$token" >> $GITHUB_ENV

      - name: Docker pull anonymously
        run: docker pull alpine:latest

      - name: Check Rate Limits
        run: |
          # 取得したトークンをAuthorizationヘッダにセットしてHEADリクエスト
          response=$(curl -s -I -H "Authorization: Bearer $token" https://registry-1.docker.io/v2/library/alpine/manifests/latest)
          
          echo "$response"
          echo "----"

          remaining=$(echo "$response" | grep -i "RateLimit-Remaining" | awk '{print $2}')
          echo "RateLimit-Remaining: $remaining"
